name: Trivy Scan with Slack Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: docker build -t my-image-name .

    - name: Install Trivy
      run: |
        sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Scan Docker image with Trivy
      id: trivy_scan
      run: trivy image --exit-code 1 --severity HIGH,CRITICAL my-image-name
      continue-on-error: true

    - name: Send Slack Notification
      if: failure()  # Trivy 스캔이 실패했을 때만 실행
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "Trivy 스캔에서 취약점이 발견되었습니다. 확인이 필요합니다.",
          "attachments": [
            {
              "color": "#FF0000",
              "title": "Trivy Scan Failed",
              "text": "취약점이 발견된 Docker 이미지: my-image-name"
            }
          ]
        }' $SLACK_WEBHOOK_URL
